name: CI Checks

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  betterleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dortort/betterleaks-action@v0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: creyD/prettier_action@v4.6
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review # Change reporter.
          stylelint_input: "css/**/*.css"
  eslint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run lint:report
        continue-on-error: true
      - uses: ataylorme/eslint-annotate-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  html5validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v7
      - uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          args: --offline '.'
      - uses: peter-evans/create-issue-from-file@v6
        if: steps.lychee.outputs.exit_code != 0
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
