name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: warning
          locale: "US"
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: warning
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          stylelint_inputs: "src/css/**/*.css"
          fail_level: warning
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: "src/js/"
          fail_level: warning
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: warning
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: warning
  betterleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: 1.26
          cache: false # Otherwise it looks for go.mod.
      - run: go install github.com/betterleaks/betterleaks@latest
      - run: betterleaks git . -v
  html5validator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npx html-validate "**/*.html"
  build:
    runs-on: ubuntu-latest
    needs:
      [
        misspell,
        prettier,
        stylelint,
        eslint,
        markdownlint,
        actionlint,
        betterleaks,
        html5validator,
      ]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Step 0 - Install dependencies (Poppler)
        run: |
          sudo apt-get update -y -o Acquire::Retries=3
          sudo apt-get install -y --no-install-recommends poppler-utils

      - name: Step 1 - Copy all static src files to dist
        run: |
          mkdir -p dist
          cp -r src/* dist/

      - name: Step 2 - Create resume PDF symlink
        run: |
          files=(dist/resumes/hobbes3_resume_v*.pdf)

          if [ ${#files[@]} -eq 0 ]; then
            echo "No matching resume file found!"
            exit 1
          fi

          LATEST_FILE=$(printf '%s\n' "${files[@]}" | sort -V | tail -n1)
          echo "Latest resume file identified: $LATEST_FILE"

          TARGET_FILENAME=$(basename "$LATEST_FILE")
          ln -sf "$TARGET_FILENAME" "dist/resumes/hobbes3_resume_latest.pdf"
          echo "Successfully created symlink: dist/resumes/hobbes3_resume_latest.pdf -> $TARGET_FILENAME"

      - name: Step 3 - Convert resume PDF to PNG preview
        run: |
          pdftoppm -png -r 300 -f 1 -l 1 "dist/resumes/hobbes3_resume_latest.pdf" "dist/resumes/hobbes3_resume_latest"

          mv "dist/resumes/hobbes3_resume_latest-1.png" "dist/resumes/hobbes3_resume_latest.png"
          echo "Successfully generated resumes/hobbes3_resume_latest.png"

      - name: Step 4 - Upload dist directory as artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-build
          path: dist/
          retention-days: 1
  link-checker:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist-build
          path: dist
      - id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          workingDirectory: dist
          args: --offline --verbose --no-progress './**/*.md' './**/*.html'
          fail: false
      - if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
  lighthouse:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: dist-build
          path: dist
      - uses: treosh/lighthouse-ci-action@v12
        with:
          staticDistDir: ./dist
  deploy:
    needs: [link-checker, lighthouse]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      issues: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist-build
          path: dist
      - uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy dist --project-name=site-resume
